---
abstract: 'LDAP back end for PlugAuth'
author:
  - 'Graham Ollis <gollis@sesda3.com>'
build_requires:
  FindBin: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Plugin-LDAP
requires:
  Log::Log4perl: 0
  Net::LDAP: 0
  PlugAuth: 0
  PlugAuth::Role::Auth: 0
  PlugAuth::Role::Plugin: 0
  Role::Tiny::With: 0
  perl: v5.10.0
version: 0.03
